### ISSUE TITLE
The fix is useless and must work against all lookups

### ISSUE THREAD

**Issue by xxDark** [FrankHeijden/Log4jFix#2]
See this payload for example:
${lower:${JNDI:}}

**Comment by xxDark** [comment]
There are also other keys such as `sys` or `env` that attacker might use, so.

**Comment by FrankHeijden** [comment]
Thanks for reporting, the RCE vulnerability is in the jndi key, good call on the lower case one. I will publish a fix which matches case insensitive. Since I believe the other keys are a similar attempt to check how vulnerable the server is, I will block a few others too, feel free to PR / link with more keys you believe should be blocked.

**Comment by xxDark** [comment]
You may find the list of all keys (mostly all) here: https://github.com/apache/logging-log4j2/blob/master/log4j-core/src/main/java/org/apache/logging/log4j/core/lookup/Interpolator.java#L97

**Comment by FrankHeijden** [comment]
Thanks.

**Comment by xxDark** [comment]
I would suggest almost all the keys since a lot of them may cause exceptions and potentially cause issues (for example, ${sys:} will throw an exception, since the key is empty (checked by `System#getProperty`), ${date:c} will also cause exceptions due to invalid date pattern)

**Comment by FrankHeijden** [comment]
Thanks again, https://github.com/FrankHeijden/Log4jFix/releases
